name: Analyze code statically

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using JSHint
        uses: moneyforward/jshint-action@v0
